### PR TITLE
Logans phone number in there twice.

### PR DESCRIPTION
**Pull request by jmccreight**

### CODE REVIEW

**Comment by jmccreight** [comment]
This test is failing very unexpectedly. I'm going to have to take a look and this may sit over the weekend.

**Comment by kafitzgerald** [comment]
The fail isn't just the metadata issue?

**Comment by jmccreight** [comment]
I do NOT get this error locally.... hmmm

**Comment by jmccreight** [comment]
We determined that @jmills-ncar is an xarry n00b who didnt notice that the output types were not the required types for RouteLink. We also logged #40 to trap these at run time.

**Pull request merged**
