### PR TITLE
CHANOBS output to a single file under NWM IO

### PR DESCRIPTION
**Pull request by jmccreight**
TYPE: enhancement

KEYWORDS: output, chanobs

SOURCE: j foo, n-kizzidy-car, yo

DESCRIPTION OF CHANGES: tweaks to NWM_IO output of chanobs to concatenate all time into a single file when the `split_output_count` option is set to zero. I tested a fairly limited impact of using this namelist option. 

ISSUE: I can create one. But this might raise more issues than it solves, at least for now.

TESTS CONDUCTED: 
I'm submitting this because I'm too lazy to test locally right now. But I did run the following (on cheyenne) which was satisfactory: 

```
import datetime
import deepdiff
import os
import pathlib
import pickle
import shlex
import shutil
import subprocess
import time
import wrfhydropy
import xarray as xr

config = 'nwm_ana'
domain_path = pathlib.Path('/glade/work/jamesmcc/domains/public/croton_NY')
repo_path = '/glade/u/home/jamesmcc/WRF_Hydro/wrf_hydro_nwm_public/trunk/NDHMS'
exp_path = pathlib.Path('/glade/scratch/jamesmcc/tmp_croton_reduce_output')
if not exp_path.exists():
    os.mkdir(exp_path)


run_dict = {
    'master': {'branch': 'master', 'split_output': 1},
    'single_1': {'branch': 'reduce_output', 'split_output': 1},
    'single_0': {'branch': 'reduce_output', 'split_output': 0} }

    
def run_branch_split_output(branch, split_output):

    ret = subprocess.run(shlex.split('git checkout ' + branch), cwd=repo_path)
    if ret.returncode != 0:
        raise ValueError('branch checkout failed')
    
    comp_path = exp_path / ('compile_' + branch)

    # for a fresh compile, remove comp_path from disk.
    if not comp_path.exists():
        model = wrfhydropy.Model(
            repo_path,
            model_config=config,
            compiler='ifort'
        )
        model.compile(comp_path)
    else:
        model = pickle.load((comp_path / 'WrfHydroModel.pkl').open('rb'))

    model.hydro_namelists['hydro_nlist']['split_output_count'] = split_output

    domain = wrfhydropy.Domain(
        domain_top_dir=domain_path,
        domain_config=config
    )

    model_start_time = datetime.datetime(2011, 8, 26)
    model_end_time = model_start_time + datetime.timedelta(hours=24)

    job = wrfhydropy.Job(
        exe_cmd='mpirun -np 2 ./wrf_hydro.exe',
        job_id='reduce_output',
        restart=True,
        model_start_time= model_start_time,
        model_end_time=model_end_time
    )

    sim = wrfhydropy.Simulation()
    sim.add(model)
    sim.add(domain)
    sim.add(job)

    sim_dir = exp_path / ('simulation_' + branch + '_' + str(split_output))
    if sim_dir.exists():
        shutil.rmtree(str(sim_dir))
    os.mkdir(sim_dir)
    os.chdir(sim_dir)
    sim.compose()
    sim.run()


for key, this_run_dict in run_dict.items():
    run_branch_split_output(**this_run_dict)

master_files = sorted(exp_path.glob("simulation_master_1/*CHANOBS*"))
master_ds = xr.open_mfdataset(master_files)

reduce_1_files = sorted(exp_path.glob("simulation_reduce_output_1/*CHANOBS*"))
reduce_1_ds = xr.open_mfdataset(reduce_1_files)

reduce_0_ds = xr.open_dataset(exp_path.joinpath(
    "simulation_reduce_output_0/CHANOBS_DOMAIN1.nc"))

assert (master_ds.streamflow.values == reduce_1_ds.streamflow.values).all()
assert (master_ds.streamflow.values == reduce_0_ds.streamflow.values).all()

```

NOTES: There are probably a variety of things to think about before merging this. This is very preliminary.

### Checklist
Merging the PR depends on following checklist being completed. Add `X` between each of the square 
brackets if they are completed in the PR itself. If a bullet is not relevant to you, please comment 
on why below the bullet.

 - [ ] Closes issue #xxxx (An issue must exist or be created to be closed. The issue describes and documents the problem and general solution, the PR describes the technical details of the solution.) 
 - [ ] Tests added (unit tests and/or regression/integration tests)
 - [ ] Backwards compatible
 - [ ] Requires new files? If so, how to generate them.
 - [ ] Fully documented
 - [ ] Short description in the Development section of `NEWS.md`

### CODE REVIEW

**Comment by jmccreight** [comment]
The CI tests show that when using the current setting for `split_output_count = 1` that, in just in the CHANOBS files, the `streamflow` variable has the additional, new dimension of `time`. I believe this is actually desirable and it would be wrong to write a bunch fo logic to avoid this in this case (`split_output_count = 1`). The tests I pasted above show that the data match despite this added dimension. So my opinion is that the PR should make this change to CHANOBS.

**Comment by arezoorn** [comment]
It should be notes that the `SPLIT_OUTPUT_COUNT` exists in both namelists, the one that James means in this PR refers to SPLIT_OUTPUT_COUNT in the hydro.namelist.

**Comment by arezoorn** [comment]
Note: if you submit another simulations in the same run directory, the data would be appended to the CHANOBS file. This is a desire behavior for the calibration as many times the model crashes and we do restart, then all the data would be in one file, and I just need to get rid of the duplicates in the file. This is the same behavior as `frxst_pts_out` file.

**Comment by arezoorn** [comment]
run_time

This plot shows the run time of using the combined CHANOBS versus the default which is outputting every hour. I went up to 10 years, since our spin up runs for calibration goes to 10 years, and I wanted to make sure we do not degrade the run time. I have requested 9 cores, since this is what we used for calibration, we combined 4 basins into 1 node. It actually saves time in the model run and it will save a lot of time in the read of the CHANOBS when we calculate stats (on average we spend about 10 minutes collecting the simulations values in the calibration routine, that was reduced with Prasanth changes to the code where he combine all the CHANOBS and then read it). So it is a win-win for calibration. Thanks James!!!

**Comment by jmccreight** [comment]
I bet there would be even more speed up if the file were left open. Currently the file is opened and closed with each timestep.

**Comment by jmccreight** [comment]
> It should be notes that the `SPLIT_OUTPUT_COUNT` exists in both namelists, the one that James means in this PR refers to `SPLIT_OUTPUT_COUNT` in the `hydro.namelist`.

well, this was clear in the example above, at least in wrf_hydro_py-ese:
```
model.hydro_namelists['hydro_nlist']['split_output_count'] = split_output
```

**Comment by jmccreight** [comment]
I dont know if this is helpful in a future merge scenario, but I merged nwm_v2.1-alpha4 and reduce_output branches into a new branch on my fork. 
https://github.com/jmccreight/wrf_hydro_nwm_public/blob/nwm-v2.1-alpha4_reduce_output/trunk/NDHMS/Routing/module_NWM_io.F
git was perty confused about the merge, so it was not straight forward...

**Review by kafitzgerald — APPROVED** [review]
NWM v2.1 has sailed.  

This looks good to me and as discussed today it'd be great to get this in the repo.

Failures as expected because of the added time dimension.

Should we opt for more flexibility w/ output counts in the future the structures set up here should allow for this and we can figure out the additional output files in a new PR(s).

**Comment by aubreyd** [comment]
> Note: if you submit another simulations in the same run directory, the data would be appended to the CHANOBS file. This is a desired behavior for the calibration as many times the model crashes and we do restart, then all the data would be in one file, and I just need to get rid of the duplicates when processing the CHANOBS file. This is the same behavior as `frxst_pts_out` file.

Can this be user-controlled in a namelist setting? Maybe we can leverage that RSTRT_SWC? I could see this causing issues if the user forgets to delete the file and the model just keeps appending, as this is different behavior from our standard outputs.

**Comment by jmccreight** [comment]
I agree but I think that if the option is set the run should just fail
(hopefully early). Managing files from inside fortran is not elegant or
particularly wise. There may be a solution using alternative naming
conventions, but I'm not sure that's worth the effort

-------------------------------------------------------
James L. McCreight
NCAR Research Applications Lab
office:       FL2 2065
office phone: 303-497-8404
cell:         831-261-5149

**Comment by rcabell** [comment]
Since CHANOBS is a netCDF file, appending vs replacing is very easy to do, even in Fortran.  No need to use native Fortran file-handling primitives...

**Comment by jmccreight** [comment]
replacing = clobbering? :) Someone could accidentally loose data that way.
I'm against overwriting/replacing/clobbering existing output on that basis.
I'd much rather my run failed quickly and preserved data on disk or forced
me to remove it.

-------------------------------------------------------
James L. McCreight
NCAR Research Applications Lab
office:       FL2 2065
office phone: 303-497-8404
cell:         831-261-5149

**Review by rcabell — APPROVED** [review]

**Pull request merged**
