### PR TITLE
Pull Request for Level Pool Module

### PR DESCRIPTION
**Pull request by jdmattern-noaa**
I designed and implemented the Level Pool module that creates Reservoir objects that use the Level Pool calculations within Routing. I have followed Donald Johnson and Nels Frazier's guidance for modularization with the same architecture that Donald has been using for his modules. My code development has been frequently reviewed by them. I have completed unit testing of my module and sub-modules. I also passed all of the regression tests for the nwm_ana and gridded configurations that I ran through NCAR's Docker container.

### CODE REVIEW

**Comment by jmccreight** [comment]
That all sounds great. Per 
https://github.com/NCAR/wrf_hydro_nwm_public/wiki/v5.1.0-(=-NWM-v2.0)-Versioning
serious contributions on master are not being permitted until the start of the v2.0 production run. We are going to have to develop a feature branch or a dev branch for this PR. We havent decided on the strategy, but will do so in the next few days and let you know.

**Comment by jdmattern-noaa** [comment]
Okay thank you James.

David Mattern

**Comment by jdmattern-noaa** [comment]
James,

It fails the Travis CI build. All the Docker tests pass except the gridded
perfect restart, which Joe Mills said already has a problem. I see that the
previous PR you made failed this also but was still approved. Do I need to
change anything because of this failure or should I just wait until you
create the separate branch?

Thanks,
David

**Comment by jmccreight** [comment]
the travis CI details match what you describe for local
https://travis-ci.org/NCAR/wrf_hydro_nwm_public/builds/433780182?utm_source=github_status&utm_medium=notification

you dont need to do anything related to this PR for a while.

**Comment by jdmattern-noaa** [comment]
Thanks to all of your and Laura's help, Joe! I think things are a lot
clearer, and I will help the other Water Center people that want to do same.

David

**Comment by jmccreight** [comment]
David, 
I just want to make sure you're aware that subsequent pushes to your remote branch update this pull request.

**Comment by jdmattern-noaa** [comment]
Okay thank you James. I actually forgot to unstage the Machine Learning
modules and a few other files from the PR, and I tried to do that just now.
I am fairly new to many of the features of Git. I need to retry that
because it didn't work. I will cancel this PR and submit a new one within
the hour noting that I unstaged those modules in progress, unless you
recommend otherwise.

**Pull request closed without merging**
