### PR TITLE
Rearranged  info for better readability and flow

### PR DESCRIPTION
**Pull request by mollymca**

### CODE REVIEW

**Comment by mollymca** [comment]
i changed the readme to point to the contrib guidelines, and 'committed' it, but not sure if I also need to do a new pull request?

**Comment by jmccreight** [comment]
@kafitzgerald can you update your PR. Thanks!!

**Comment by kafitzgerald** [comment]
yep, will do.

**Comment by kafitzgerald** [comment]
So this is actually @mollymca's PR + needs another review, but I'll see what I can do.  We may just close and resubmit a new PR w/ desired changes on the updated repo.

**Comment by jmccreight** [comment]
O sorry, missed it for lack of a commit message. @mollymca

**Comment by jmccreight** [comment]
I'm fighting the bot...

**Comment by jmccreight** [comment]
I was fighting the bot cause I'm to lazy to use the command to get these conflicts. ...

@mollymca 
 I'm pasting the conflicts here so you have a better starting point:

CONTRIBUTING.md:
```
<<<<<<< patch-1
=======
## Code contributions
Much of the WRF-Hydro development occurs on the public
[NCAR/wrf_hydro_nwm_public](https://github.com/NCAR/wrf_hydro_nwm_public) repository. However, some
internal development must occur on a private repository maintained by NCAR and NOAA. Due to this
dual-repository system, a strict procedure must be followed when making contributions to the WRF-
Hydro model code.

All code development contributions will be made via [forks](https://help.github.com/articles/about-forks/)
and [pull requests](https://help.github.com/articles/about-pull-requests/). If you are
unfamiliar with GitHub, forks, or pull requests, see [collaborating with issues and pull
requests](https://help.github.com/categories/collaborating-with-issues-and-pull-requests/) for a
thorough guide to collaborating on GitHub.
>>>>>>> master
```
and 
```
<<<<<<< patch-1
=======

### Types of contributions
#### Bug fixes
All bug fixes must address a specific [GitHub
issue](https://github.com/NCAR/wrf_hydro_nwm_public/issues). Only issues labeled with "Community
dev" are open to community contributions. The majority of issues will be open to community
contributions, but some cases may require more careful handling. Issues without the "Community dev"
label are either still being investigated, are of broad scope, or involve changes to code that is
actively being developed internally.

All code changes to address issues must be submitted using a pull request, and the corresponding
issue number must be referenced in the pull request. For more information on referencing issues,
see [issues and keywords](https://help.github.com/articles/closing-issues-using-keywords/).

#### New features
Code contributions for minor model enhancements or new features follow a similar pattern to bug
fixes. The proposed feature must be submitted as a GitHub issue and all discussions regarding the
new feature should reside in the issue thread. Additionally, work should not begin on the new
feature until the issue has been tagged with "Community dev".

Depending on the scope of the new feature, a WRF-Hydro core contributor may suggest you create a
[branch](https://help.github.com/articles/about-branches/) to hold all development for the new
feature.

#### Research development
Larger-scale research development, e.g. model coupling, must be coordinated with a WRF-Hydro team
member prior to beginning work. This type of development may impact other community projects and
requires more careful governance to help steer the direction of model development and maximize
harmony among the various NCAR, NOAA, and WRF-Hydro community research efforts.
>>>>>>> master
```

README.md:
```
<<<<<<< patch-1
If you have found a bug or would like to propose changes to the model code please refer to our [contributing guidelines](.github/CONTRIBUTING.md).
=======
If you have found a bug or would like to propose changes to the model code please submit an issue [here on GitHub](https://github.com/NCAR/wrf_hydro_nwm_public/issues).
>>>>>>> master
```

**Comment by kafitzgerald** [comment]
Just worked w/ Molly to move edits to a new PR so this can just remain closed.

**Pull request closed without merging**
