### PR TITLE
Change to musking-cunge in module_channel_routing.F to cause a fail i…

### PR DESCRIPTION
**Pull request by jmills-ncar**
…n regression test against master

### CODE REVIEW

**Comment by jmills-ncar** [comment]
👍 Failed as expected, closing

**Comment by hydro-automerge** [comment]
## Difference plots for configuration 'reach_lakes'
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text

**Comment by hydro-automerge** [comment]
## Difference plots for configuration 'gridded'
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text

**Comment by hydro-automerge** [comment]
## Difference plots for configuration 'reach'
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text

**Comment by hydro-automerge** [comment]
## Difference plots for configuration 'reach_lakes'
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text

**Comment by hydro-automerge** [comment]
## Difference plots for configuration 'gridded'
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text

**Comment by hydro-automerge** [comment]
## Difference plots for configuration 'nwm_long_range'
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text

**Comment by hydro-automerge** [comment]
## Difference plots for configuration 'reach'
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text

**Comment by hydro-automerge** [comment]
## Difference plots for configuration 'reach_lakes'
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text

**Pull request closed without merging**
