### PR TITLE
Auto-generation and posting of model difference plots for CI tests

### PR DESCRIPTION
**Pull request by andygaydos**
TYPE: enhancement
KEYWORDS: testing, plots, difference
SOURCE: Andy Gaydos, NCAR/RAL 
DESCRIPTION OF CHANGES: 

The current action when the CI tests detect model output differences is to print numerical output to the test log(s) using `ncdiff`. This PR adds code to generate plots of output differences, and automatically adds them to the PR comments, when a CI tests fails. 

Plots are generated for both gridded file field differences (in the form of 2D 'heat maps'), and for vector file differences (boxplot spread of differences for each feature/id, as well as time series comparisons for select features). 

A subset of fields to plot (when differences are detected) is defined in the `plot_diffs()` function of `tests/utilities.py`. Minimum thresholds for each field are defined in `tests/local/utils/thresholds.csv`. (Differences are only detected and plotted above this threshold). For vector differences, a list of feature_ids to plot is contained in the domain tarball (e.g. croton.tar.gz) in `example_case/testing_diff_feature_ids.json`

Plot images are uploaded to a dedicated image repository on Github, where they are linked as PR comments by the 'hydro-automerge' github user.

### CODE REVIEW

**Comment by hydro-automerge** [comment]
## Difference plots for configuration 'reach'
alt text
alt text
alt text
alt text
alt text

**Comment by hydro-automerge** [comment]
## Difference plots for configuration 'nwm_long_range'
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text

**Comment by hydro-automerge** [comment]
## Difference plots for configuration 'nwm_ana'
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text

**Comment by hydro-automerge** [comment]
## Difference plots for configuration 'reach'
alt text
alt text
alt text
alt text
alt text
alt text
alt text

**Comment by hydro-automerge** [comment]
## Difference plots for configuration 'gridded'
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text

**Comment by hydro-automerge** [comment]
## Difference plots for configuration 'nwm_long_range'
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text

**Comment by hydro-automerge** [comment]
## Difference plots for configuration 'nwm_ana'
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text

**Comment by hydro-automerge** [comment]
## Difference plots for configuration 'reach'
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text

**Comment by hydro-automerge** [comment]
## Difference plots for configuration 'nwm_long_range'
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text

**Comment by hydro-automerge** [comment]
## Difference plots for configuration 'gridded'
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text

**Comment by hydro-automerge** [comment]
## Difference plots for configuration 'nwm_ana'
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text
alt text

**Review by rcabell — APPROVED** [review]

**Pull request merged**
