### PR TITLE
Updates to testing and lakefix changes

### PR DESCRIPTION
**Pull request by jmills-ncar**
This PR passes testing on the new croton domain

### CODE REVIEW

**Comment by jmills-ncar** [comment]
```####################################
### TESTING:  ---  gridded  ---  ###
####################################

pytest -vv --tb=no --ignore=local -p no:cacheprovider  -s --ignore=tests/test_supp_1_channel_only.py  --html=/home/docker/test_out/wrfhydro_testing-gfort-gridded.html --self-contained-html --config gridded --compiler gfort --domain_dir /home/docker/example_case --candidate_dir /home/docker/test_out/candidate_can_pytest/trunk/NDHMS --reference_dir /home/docker/test_out/reference_ref_pytest/trunk/NDHMS --output_dir /home/docker/test_out --ncores 2
=================================================================================================== test session starts ====================================================================================================
platform linux -- Python 3.6.5, pytest-3.8.0, py-1.6.0, pluggy-0.7.1 -- /home/docker/miniconda3/bin/python
metadata: {'Python': '3.6.5', 'Platform': 'Linux-4.9.93-linuxkit-aufs-x86_64-with-debian-stretch-sid', 'Packages': {'pytest': '3.8.0', 'py': '1.6.0', 'pluggy': '0.7.1'}, 'Plugins': {'metadata': '1.7.0', 'html': '1.19.0', 'datadir-ng': '1.1.0'}}
rootdir: /home/docker, inifile:
plugins: metadata-1.7.0, html-1.19.0, datadir-ng-1.1.0
collected 9 items

tests/test_1_fundamental.py::test_compile_candidate
Question: The candidate compiles?


Model successfully compiled into /home/docker/test_out/gridded/compile_candidate
PASSED
tests/test_1_fundamental.py::test_compile_reference
Question: The reference compiles?


Model successfully compiled into /home/docker/test_out/gridded/compile_reference
PASSED
tests/test_1_fundamental.py::test_run_candidate
Question: The candidate runs successfully?


Composing simulation into directory:'/home/docker/test_out/gridded/run_candidate'
Getting domain files...
Making job directories...
Validating job input files
run_candidate
Model already compiled, copying files...
Simulation successfully composed

waiting for job to complete...
Running job run_candidate:
    Wall start time: 2018-10-18 21:36:53
    Model start time: 2011-08-26 00:00
    Model end time: 2011-09-01 00:00
PASSED
tests/test_1_fundamental.py::test_run_reference
Question: The reference runs successfully?


Composing simulation into directory:'/home/docker/test_out/gridded/run_reference'
Getting domain files...
Making job directories...
Validating job input files
run_reference
Model already compiled, copying files...
Simulation successfully composed

waiting for job to complete...
Running job run_reference:
    Wall start time: 2018-10-18 21:37:13
    Model start time: 2011-08-26 00:00
    Model end time: 2011-09-01 00:00
PASSED
tests/test_1_fundamental.py::test_ncores_candidate
Question: The candidate outputs from a ncores run match outputs from ncores-1 run?


Composing simulation into directory:'/home/docker/test_out/gridded/ncores_candidate'
Getting domain files...
Making job directories...
Validating job input files
ncores_candidate
Model already compiled, copying files...
Simulation successfully composed

waiting for job to complete...
Running job ncores_candidate:
    Wall start time: 2018-10-18 21:37:33
    Model start time: 2011-08-26 00:00
    Model end time: 2011-09-01 00:00
PASSED
tests/test_1_fundamental.py::test_perfrestart_candidate
Question: The candidate outputs from a restart run match the outputs from standard run?


Composing simulation into directory:'/home/docker/test_out/gridded/restart_candidate'
Getting domain files...
Making job directories...
Validating job input files
run_candidate
Model already compiled, copying files...
Simulation successfully composed

waiting for job to complete...
Running job run_candidate:
    Wall start time: 2018-10-18 21:37:54
    Model start time: 2011-08-29 00:00
    Model end time: 2011-09-01 00:00
PASSED
tests/test_2_regression.py::test_regression_data
Question: The candidate run data values match the reference run?


PASSED
tests/test_2_regression.py::test_regression_metadata
Question: The candidate run output metadata match the reference run?


PASSED
tests/test_3_outputs.py::test_output_has_nans
Question: Outputs from all tests are free of nans in data and attributes


PASSED

---------------------------------------------------------------------- generated html file: /home/docker/test_out/wrfhydro_testing-gfort-gridded.html ----------------------------------------------------------------------
===================================================================================================== warnings summary =====================================================================================================
/home/docker/miniconda3/lib/python3.6/site-packages/wrfhydropy/core/simulation.py:225: UserWarning: Model minor versions v5.0.2 do not match domain minor versions v5.0.3
  domain.compatible_version)

/home/docker/miniconda3/lib/python3.6/site-packages/wrfhydropy/core/simulation.py:225: UserWarning: Model minor versions v5.0.2 do not match domain minor versions v5.0.3
  domain.compatible_version)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
========================================================================================== 9 passed, 2 warnings in 92.24 seconds ===========================================================================================


##################################
###  ---  TESTING PASSED  ---  ###
##################################
```

**Comment by jmills-ncar** [comment]
This PR includes updates to testing as well as changes in pr #205 .

pr #205 was included here to make sure that testing passed with the recent changes to lake code, which required a new model spinup.

**Comment by jmills-ncar** [comment]
@aubreyd This passed local testing and is now running in CI. If it passes CI then I just need your signoff that all your changes went in. I believe they did but would like your confirmation

**Comment by jmills-ncar** [comment]
**NOTE** This PR will fail regression because of a new variable added

**Comment by aubreyd** [comment]
Looks good to me!

**Pull request merged**
