### PR TITLE
Minor hardening of nudging timeslice path to force include "/" 

### PR DESCRIPTION
**Pull request by jmccreight**
TYPE: bug-ish fix
KEYWORDS: nudging
SOURCE: james, nCAR
DESCRIPTION OF CHANGES: Simply force append "/" to the supplied nudging path
ISSUE: none

TESTS CONDUCTED: just CI locally

### Checklist
Merging the PR depends on following checklist being completed. Add `X` between each of the square 
brackets if they are completed in the PR itself. If a bullet is not relevant to you, please comment 
on why below the bullet.

 - [ ] Closes issue #xxxx (An issue must exist or be created to be closed. The issue describes and documents the problem and general solution, the PR describes the technical details of the solution.) 
 - [ ] Tests added (unit tests and/or regression/integration tests)
 - [ ] Backwards compatible
 - [ ] Requires new files? If so, how to generate them.
 - [ ] Fully documented
 - [ ] Short description in the Development section of `NEWS.md`

### CODE REVIEW

**Comment by kafitzgerald** [comment]
@jmccreight should we send this to the v5.2.0 branch first?

**Comment by jmccreight** [comment]
yes

**Comment by jmccreight** [comment]
Hm. not sure what that's failing

**Comment by jmccreight** [comment]
I wonder if it's gnu vs intel. I tested AnA using intel

**Comment by rcabell** [comment]
Yeah, but it's failing the reference too

**Comment by rcabell** [comment]
Probably because the domain isn't tagged with v5.2.0

**Comment by jdmattern-noaa** [comment]
Thanks for adding this, James and Ryan. A '/' should also added in the same corresponding spot for the RFC reader:
https://github.com/NCAR/wrf_hydro_nwm_public/blob/master/trunk/NDHMS/Routing/Reservoirs/module_reservoir_read_rfc_time_series_data.F#L169

**Pull request merged**
