### PR TITLE
Add new feature contributor checklist to contributor guidelines.

### PR DESCRIPTION
**Pull request by aubreyd**
TYPE:  text only

KEYWORDS: guidelines

SOURCE: Aubrey, NCAR 

DESCRIPTION OF CHANGES: Add new feature contributor checklist to contributor guidelines.

TESTS CONDUCTED: N/A

### CODE REVIEW

**Comment by kafitzgerald** [comment]
@aubreyd looks like some other unrelated changes got added to this and we probably want to PR to v5.2.x.  

Looks good otherwise.

**Review by rcabell — CHANGES_REQUESTED** [review]
It looks like some changes to `module_lsm_forcing.F` got mixed into this. I'm guessing this is unintentional...

**Comment by aubreyd** [comment]
Ah - I see. Since I submitted this in August I made an update to my master that it automatically brought in...? I guess I should have put the original PR in from a standalone branch...?

**Comment by kafitzgerald** [comment]
Our bad for not merging sooner, but generally a cleaner approach.  

Should be pretty easy to just copy over the single file.

**Comment by aubreyd** [comment]
OK, will resubmit from another branch.

**Pull request closed without merging**
