### PR TITLE
Restore older PGI compiler compatibility

### PR DESCRIPTION
**Pull request by rcabell**
**TYPE**: Bugfix

**KEYWORDS**: PGI, build

**SOURCE**: Ryan Cabell (NCAR)

**REFERENT ISSUE**: #313

**DESCRIPTION OF CHANGES:**

Instead of calling Fortran 2008 `ERROR STOP` statement which is unsupported by some compilers, changed to the existing `FATAL_ERROR_STOP()` subroutine that was already in `module_mpp_land`. Cleaned up that subroutine as well, using `error_unit` instead of hard-coding 6 (magic number!)

**TESTS CONDUCTED:**

Code now compiles on PGI 15.7.

### CODE REVIEW

**Comment by kafitzgerald** [comment]
Actually, does this need to go to the v5.1.1 branch first?

**Comment by rcabell** [comment]
> Actually, does this need to go to the v5.1.1 branch first?

Sure, it's a low priority and it would be merged back into `master` when the whole v5.1.1 branch is...

**Comment by rcabell** [comment]
I rebased this PR from `v5.1.1` to `master`, no other changes but will require re-review

**Comment by afanfa** [comment]
Thanks @rcabell , it looks good to me.

**Pull request merged**
