### PR TITLE
Reservoir restarts

### PR DESCRIPTION
**Pull request by jdmattern-noaa**
This reservoir-restarts branch is branched off of level-pool that I previously submitted. Reservoir inflows, outflows, and water elevations are written to and read from a separate reservoir restart file. This PR still writes/reads the corresponding qlakei, qlakeo, and resht to/from the hydro restart files, though I will deactivate this in a following PR. Parallel NetCDF operations are required for this because the reservoir objects are distributed across multiple processors, and each reservoir object handles its own input/output. Nels Frazier and I will collaborate with Ryan Cabell, James McCreight, and Laura Read to update the necessary libraries and domain environment and include a reservoir restart file for the restart tests.

### CODE REVIEW

**Comment by hellkite500** [comment]
If you want to update the testing wrfhydro docker image, consider using one of the parallel hdf5 packages you can find here:
https://launchpad.net/ubuntu/+source/hdf5

**Comment by jmccreight** [comment]
@jdmattern-noaa Why does CI fail?

**Comment by jdmattern-noaa** [comment]
@jmccreight @rcabell 
The Docker environment needs to support parallel NetCDF write operations. As with your guidance for the ML testing, I modified the croton_ny domain to handle a 'reservoir_restart_file' in hydro_namelist running in the Docker container. It failed though as expected when it tried to create a NetCDF file to write in parallel.

Nels took a look at the Docker config and suggests at https://github.com/NCAR/wrf_hydro_docker/blob/4d3b8e4e18d65f9c00df259a91771a0203f76b94/dev/base/Dockerfile#L45 to instead use libhdf5-mpich-dev, available here: https://packages.ubuntu.com/xenial/libhdf5-mpich-dev 

Then no need to build mpich from source, only have to change HDF5 env varaibles to point to right location based on libhdf5-mpich-dev install.
This "should" allow netcdf to build parallel support...

Please let me know once you have this updated, so that I can run my tests. I will then send you and Ryan my modified croton_ny domain.

**Comment by jmccreight** [comment]
Thanks. I thought it would fail at compile, but now I see why it fails during run time. 
 @jdmattern-noaa can you fix the merge conflicts resulting from the level-pool merge?

**Comment by jdmattern-noaa** [comment]
Sure. Will get to shortly. Thanks.

**Comment by jmccreight** [comment]
@jdmattern-noaa  
cc4c0dc looks like a mistake. Can you force push e27ece?
When I suppress whitespace diffs: 
image

**Comment by jdmattern-noaa** [comment]
@jmccreight It is now reset to that commit. Thanks.

**Comment by rcabell** [comment]
@jdmattern-noaa -- I'm trying to run some tests with this PR on Cheyenne and seeing MPI crashes. What combination of compiler/MPI/netcdf-parallel did you originally develop this against?

**Comment by hellkite500** [comment]
Can you paste some output of the crash?

**Comment by rcabell** [comment]
> Can you paste some output of the crash?
> […](#)

```
MPT ERROR: Rank 0(g:0) is aborting with error code 1.
	Process ID: 32297, Host: r5i5n3, Program: /gpfs/fs1/work/rcabell/rr/front_range/wrf_hydro.exe
	MPT Version: HPE MPT 2.19  12/07/18 05:31:15

MPT: --------stack traceback-------
 ---
 FATAL ERROR! Program stopped. Recompile with environment variable HYDRO_D set t
 o 1 for enhanced debug information.
```
I've traced the problem to line 31 in module_reservoir_io.F:

```
call check(nf90_create( trim(out_file), IOR(NF90_NETCDF4, NF90_MPIPOSIX), ncid, comm=MPI_COMM_WORLD, 
        info=MPI_INFO_NULL), 'create_reservoir_restart_file')
```

A similar error occurs when using Intel MPI, and various version of Intel and gfortran have similar erors.

**Comment by hellkite500** [comment]
@rcabell not as informative as one would hope for. Can you also run a `module show` and post the output? This seems familiar, but will take some investigation. I'll find out the exact library versions tomorrow for mpi, hdf5, and netcdf that were successful locally.

**Comment by hellkite500** [comment]
So I knew that error line looked familiar. The program is calling hydro_stop, which happens from the check call when an error creating the file occurs. That error message is passed to hydro stop and should give some clue as to why netcdf couldn't create the file. Can you grep the diag.xxxx files for FATAL and see if there is any other diagnostic information?

**Comment by jdmattern-noaa** [comment]
@rcabell On my VM, I have netcdf-openmpi-4.3.3.1 and hdf5-openmpi-devel-1.8.12 linked to openmpi-devel-1.10.7

I will add the file name to that check call in a few minutes and push that update.

**Comment by rcabell** [comment]
On cheyenne, with various combinations of compilers and mpi libraries, the error is always the same:

`Permission denied for reservoir restart file from function create_reservoir_restart_file`

Which is odd, since other files are being written to the run directory just fine.

For reference, current default module set is:
``` 
  1) nco/4.6.2     3) python/3.6.8   5) ncarcompilers/0.4.1   7) impi/2017.1.132
  2) ncarenv/1.2   4) intel/17.0.1   6) netcdf-mpi/4.5.0
```

**Comment by hellkite500** [comment]
> On cheyenne, with various combinations of compilers and mpi libraries, the error is always the same:
> 
> `Permission denied for reservoir restart file from function create_reservoir_restart_file`
> 
> Which is odd, since other NetCDF files are being written to the run directory just fine.
> 
> For reference, current default module set is:
> 
> ```
>   1) nco/4.6.2     3) python/3.6.8   5) ncarcompilers/0.4.1   7) impi/2017.1.132
>   2) ncarenv/1.2   4) intel/17.0.1   6) netcdf-mpi/4.5.0
> ```

I spent some time on this issue, and haven't been able to pinpoint what is happening.  I have tracked it down to a potential handling of the `cmode` flags to `nf90_create`.  Running the same create without parallel flags/options works fine, no permission denied.  Changing the `cmode` flags to not include parallel modes causes a different error (illegal argument error, which is expected).  I also tried both `NF90_MPIPOSIX` and `NF90_MPIIO`, both give the same permission error.  After eliminating all avenues of permission settings on the file system, I submitted an e-mail to Unidata support to see if they can shed some light on the issue.  I may pull the netcdf source and make a debug build so I can step into the netcdf handling and see if I can learn more.

**Comment by jmccreight** [comment]
@hellkite500 
What's the status? I think it's probably easiest if you guys can just write the MPI gather so that this runs on CI and we can get it merged. We really need a version that does not rely on new external libraries before we could move to the next step of requiring them and enhancing functionality.

**Pull request closed without merging**
