### PR TITLE
Linking wrf_hydro_nwm_public to noahmp respository

### LINKED ISSUE #494: Link wrf_hydro_nwm_public repository to noahmp repository
To consolidate Noah-MP model development efforts, a single repository has been created so multiple parent systems can access the same Noah-MP code base:

https://github.com/NCAR/noahmp

A link needs to be made via submodules to the above repository and removal of noahmplsm module (module_sf_noahmplsm.F) and parameter table (MPTABLE.TBL)  from the wrf_hydro_nwm_public repo.

### PR DESCRIPTION
**Pull request by barlage**
This is what's going on for linking noahmp repository to wrf_hydro_nwm_public. Open for comments.

TYPE: new feature

KEYWORDS: noahmp

SOURCE: Michael Barlage, NCAR

DESCRIPTION OF CHANGES: Adding link to noahmp repository via submodules

ISSUE: 
```
Fixes #494 
```

TESTS CONDUCTED: Small, short reproducibility tests run

NOTES:

### Checklist
Merging the PR depends on following checklist being completed. Add `X` between each of the square 
brackets if they are completed in the PR itself. If a bullet is not relevant to you, please comment 
on why below the bullet.

 - [ ] Closes issue #xxxx (An issue must exist or be created to be closed. The issue describes and documents the problem and general solution, the PR describes the technical details of the solution.) 
 - [ ] Tests added (unit tests and/or regression/integration tests)
 - [ ] Backwards compatible
 - [ ] Requires new files? If so, how to generate them.
 - [ ] Fully documented
 - [ ] Short description in the Development section of `NEWS.md`

### CODE REVIEW

**Comment by andrewsoong** [comment]
@barlage can wrf_hydro run with crop and irrigation? Thanks!

**Comment by andrewsoong** [comment]
> Hello @andrewsoong I no longer work on this project so I'll direct you to @prasanthvkrishna and @ncarchen

Thanks! @barlage

**Comment by andrewsoong** [comment]
> Hello @andrewsoong I no longer work on this project so I'll direct you to @prasanthvkrishna and @ncarchen

Thanks! @barlage

**Comment by rcabell** [comment]
Closing due to new approach (will be new PR)

**Pull request closed without merging**
