### PR TITLE
Update NUOPC cap exchange fields

### PR DESCRIPTION
**Pull request by danrosen25**
TYPE: enhancement

KEYWORDS: ESMF, NUOPC, UFSATM, RRFS

SOURCE: Daniel Rosen, NCAR

DESCRIPTION OF CHANGES: Updated NUOPC cap with additional fields for coupling to UFSATM (for RRFS-NWM coupling project). Moved field related code to separate file. Added configuration options for fields.

Included in PR
* Add 3 dimensional soil fields smc, slc, stc (for coupling to UFSATM)
* Update LSM forcings check (check for 2d or 3d import fields to run with coupled forcings)
* Update NUOPC cap fill values
* Add options for memory copy or pointer
* Add options to initialize with prescribed values
* Add options to check for missing values
* Add options to fill missing values with prescribed values
* Move fields utilities to WRFHydro_NUOPC_Fields.F90 (code cleanup)
* Cleanup ESMF extension utilities
* Set field timestamp to invalid for coldstarts (so that coupled models don't accept data as current)

ISSUE: none

TESTS CONDUCTED: Tested in [RRFS-NWM](https://github.com/NESII/ufs-srweather-app/tree/feature/RRFS_NWM_dev) coupling and [LIS-WRFHYDRO](https://github.com/NESII/lishydro/tree/feature/parflow) coupling.

**RRFS-NWM**
workflow for coupled run is incomplete and requires manual steps that are not part of repo

**LIS-Hydro (on Cheyenne)**
1. checkout: git clone -b feature/parflow --recursive git@github.com:NESII/lishydro.git
2. configure: ./configure.sh
3. build: ./build.sh
4. setup usecase(example coupled_tuolumne.noahmp.nldas2): ./setuprun.sh coupled_tuolumne.noahmp.nldas2
5. cd run/coupled_tuolumne.noahmp.nldas2 
6. run usecase : qsub run.sh

NOTES: 

New Cap Configuration Options:
- field_memory_import: copy field to internal memory or use array pointer
- field_memory_export: copy field from internal memory or use array pointer
- initialize_import: initialize import with missing values, zeros, external model coupling, prescribed data, from restart file, or model state (default)
- initialize_export: initialize import with missing values, zeros, prescribed data, from restart file, or model state (default)
- missing_import: handle missing import data - fail if import missing (default), prescribe values to missing cells, ignore missing cells
- reset_import: reset import data to missing value after ModelAdvance

### Checklist
Merging the PR depends on following checklist being completed. Add `X` between each of the square 
brackets if they are completed in the PR itself. If a bullet is not relevant to you, please comment 
on why below the bullet.

 - [ ] Closes issue #xxxx (An issue must exist or be created to be closed. The issue describes and documents the problem and general solution, the PR describes the technical details of the solution.) 
 - [ ] Tests added (unit tests and/or regression/integration tests)
 - [x] Backwards compatible
 - [ ] Requires new files? If so, how to generate them.
 - [ ] Documentation included
 - [ ] Short description in the Development section of `NEWS.md`

### CODE REVIEW

**Comment by danrosen25** [comment]
Hi @rcabell @kafitzgerald 
Do you have a timeline for reviewing this change? If you'd like we can schedule a formal code review.

**Comment by rcabell** [comment]
@danrosen25 -- since this doesn't touch the main body of the WRF-Hydro code, and therefore isn't really exercised by the automated regression testing, I'll defer to you to indicate it's readiness. 

By the way, does this PR integrate with (or obviate) your other PRs that were in Draft status? (#550 and #578)

**Review by rcabell — DISMISSED** [review]

**Comment by danrosen25** [comment]
I tested the changes in two coupled systems, one for the additional features and one for backwards compatibility. I'll have to update (#550 and #578). I should be able to make progress on the GNU build but I need a collaborative decision for the zsoil issue.

**Comment by rsdunlapiv** [comment]
@rcabell @scrasmussen @kafitzgerald what is the status of the merge of this PR?  We are waiting for this merge in order to tag the upstream "LISHydro" repository, which points to WRF-Hydro as a submodule.  Any update would be appreciated!

**Comment by rcabell** [comment]
> @rcabell @scrasmussen @kafitzgerald what is the status of the merge of this PR? We are waiting for this merge in order to tag the upstream "LISHydro" repository, which points to WRF-Hydro as a submodule. Any update would be appreciated!

Hi Rocky -- sorry for the delay here, we are hoping to get it reviewed this week. I spoke briefly to Dan about it on Tuesday and he will get the branch rebased to the current WRF-Hydro `master` and then we can move pretty quickly. I'll keep you in the loop.

**Review by rcabell — APPROVED** [review]

**Review by scrasmussen — APPROVED** [review]
CI checks pass and scanning through code nothing seems to stand out to prevent it from being accepted. LGTM

**Pull request merged**
