### PR TITLE
Groundwater option - exponential w/ area normalization - part II

### PR DESCRIPTION
**Pull request by kafitzgerald**
This PR turns on the new groundwater option introduced in PR #338 in testing and documented in issue #354.

From the previous PR:

> This PR adds an additional bucket model option GWBASESWCRT=4 for the UDMAP=1 (i.e. NWM) configuration of the model per discussion / documentation in issue #354 .

>The formulation is a modification of the current GWBASESWCRT=1 exponential model, but normalized to the area of the catchment / bucket so that parameters can be better regionalized.

>Namelist changes: Additional option number available for GWBASESWCRT

>Parameter file changes: No changes required

>Testing updates: GWBASESWCRT=4 will be the default option for NWM configuration tests

>Test results from CONUS simulations are included via the link below.

[Link](https://docs.google.com/presentation/d/1K3snxzjUbWvyVnqXdOa7ofUeHvFr6vt7GEsD2ik5Ktw/edit?usp=sharing) with plots from test simulations.

### CODE REVIEW

**Comment by kafitzgerald** [comment]
Regression fails for NWM AnA and Long Range in the channel and buckets as expected.

**Comment by kafitzgerald** [comment]
[Link](https://docs.google.com/presentation/d/1K3snxzjUbWvyVnqXdOa7ofUeHvFr6vt7GEsD2ik5Ktw/edit?usp=sharing) with CONUS simulation plots.

**Comment by rcabell** [comment]
CONUS testing passed except for regression, as expected. AnA diffs are attached here:

```
{'channel_rt': 2, 'chanobs': 2, 'lakeout': 2, 'gwout': 2, 'rtout': 0, 'ldasout': 0, 'restart_hydro': 2, 'restart_lsm': 0, 'restart_nudging': 2}

channel_rt

     Variable    Count           Sum  ...     Range   Mean  StdDev
0  streamflow  2685383 -1.298881e+07  ...  5913.640 -4.837  71.223
1       nudge      142  0.000000e+00  ...     0.000  0.000   0.000
2   q_lateral  2724813  2.412342e+05  ...    68.300  0.089   0.217
3    velocity  2679107  3.501369e+05  ...     9.693  0.131   0.170
4        Head  2740898  1.899193e+05  ...    84.207  0.069   0.907

[5 rows x 8 columns]
     Variable    Count          Sum       Min      Max     Range   Mean  StdDev
0  streamflow  2685363 -8784303.246 -6243.326  558.306  6801.631 -3.271  68.889
1       nudge      194        0.000    -0.000    0.000     0.000  0.000   0.000
2   q_lateral  2713665    87309.361   -51.467    3.568    55.034  0.032   0.122
3    velocity  2679070   181699.702    -4.867    3.322     8.189  0.068   0.107
4        Head  2736668   190662.620   -53.803    8.496    62.298  0.070   0.619

chanobs

     Variable  Count         Sum       Min      Max     Range    Mean   StdDev
0  streamflow   7976 -241604.717 -3872.162  361.367  4233.529 -30.291  149.333
     Variable  Count         Sum      Min      Max     Range    Mean  StdDev
0  streamflow   7976 -118274.383 -4623.49  518.101  5141.591 -14.829  125.59

lakeout

         Variable  Count        Sum       Min      Max     Range   Mean  StdDev
0  water_sfc_elev   5103   -722.781    -4.910    1.063     5.972 -0.142   0.344
1          inflow   5184 -43876.421 -1934.993  446.824  2381.818 -8.464  79.001
2         outflow   5096 -47444.721  -801.556  116.346   917.901 -9.310  43.060
         Variable  Count        Sum       Min      Max     Range   Mean  StdDev
0  water_sfc_elev   5099   -309.801    -5.221    0.887     6.108 -0.061   0.252
1          inflow   5184 -16117.478 -2621.742  701.950  3323.693 -3.109  65.595
2         outflow   5092 -26336.043 -1162.541  108.815  1271.357 -5.172  35.872

gwout

  Variable    Count          Sum     Min     Max   Range   Mean  StdDev
0  outflow  2724818   241234.231 -63.205   5.094  68.300  0.089   0.217
1    depth  2724818  3648120.468 -12.464  46.748  59.212  1.339   2.801
  Variable    Count          Sum     Min     Max   Range   Mean  StdDev
0  outflow  2713702    87309.361 -51.467   3.568  55.034  0.032   0.122
1    depth  2724823  1771224.324 -12.345  47.940  60.285  0.650   1.859

restart_hydro

None
     Variable    Count           Sum  ...     Range   Mean  StdDev
0       hlink  2740898  1.899193e+05  ...    84.207  0.069   0.907
1      qlink1  2685383 -1.298881e+07  ...  5913.640 -4.837  71.223
2      qlink2  2685383 -1.298881e+07  ...  5913.640 -4.837  71.223
3       resht     5103 -7.227810e+02  ...     5.972 -0.142   0.344
4      qlakeo     5096 -4.744472e+04  ...   917.901 -9.310  43.060
5      qlakei     5184 -4.387642e+04  ...  2381.818 -8.464  79.001
6  z_gwsubbas  2724818  3.648120e+03  ...     0.059  0.001   0.003

[7 rows x 8 columns]
     Variable    Count          Sum       Min      Max     Range   Mean  StdDev
0       hlink  2736668   190662.620   -53.803    8.496    62.298  0.070   0.619
1      qlink1  2685363 -8784303.246 -6243.326  558.306  6801.631 -3.271  68.889
2      qlink2  2685363 -8784303.246 -6243.326  558.306  6801.631 -3.271  68.889
3       resht     5099     -309.801    -5.221    0.887     6.108 -0.061   0.252
4      qlakeo     5092   -26336.043 -1162.541  108.815  1271.357 -5.172  35.872
5      qlakei     5184   -16117.478 -2621.742  701.950  3323.693 -3.109  65.595
6  z_gwsubbas  2724823     1771.224    -0.012    0.048     0.060  0.001   0.002

restart_nudging

  Variable  Count  Sum  Min  Max  Range  Mean  StdDev
0    nudge    142  0.0  0.0  0.0    0.0   0.0     0.0
  Variable  Count  Sum  Min  Max  Range  Mean  StdDev
0    nudge    194  0.0 -0.0  0.0    0.0   0.0     0.0```

@kafitzgerald, if you're still happy with these, I will approve/merge this PR.

**Comment by rcabell** [comment]
CONUS testing passed except for regression, as expected. Long-Range diffs are attached here:

```
{'channel_rt': 2, 'chanobs': 2, 'lakeout': 2, 'gwout': 2, 'ldasout': 0, 'restart_hydro': 2, 'restart_lsm': 0, 'restart_nudging': 2}

channel_rt

     Variable    Count          Sum       Min      Max     Range   Mean  StdDev
0  streamflow  2685438 -6895576.734 -2436.044  428.897  2864.941 -2.568  36.328
1       nudge       49        0.000     0.000    0.000     0.000  0.000   0.000
2   q_lateral  2724837   158617.749   -52.146    4.825    56.971  0.058   0.147
3    velocity  2680318   326556.976    -6.438    3.423     9.861  0.122   0.154
4        Head  2745286   120932.399   -44.844    9.954    54.798  0.044   0.606
     Variable    Count          Sum       Min      Max     Range   Mean  StdDev
0  streamflow  2685413 -4373101.503 -2368.893  268.248  2637.141 -1.628  33.486
1       nudge       87        0.000     0.000    0.000     0.000  0.000   0.000
2   q_lateral  2724832    65530.238   -34.304    3.244    37.548  0.024   0.087
3    velocity  2680274   214076.523    -4.526    2.539     7.065  0.080   0.112
4        Head  2739774   175008.271   -38.326    6.697    45.023  0.064   0.444

chanobs

     Variable  Count         Sum      Min     Max     Range    Mean  StdDev
0  streamflow   7976 -138629.681 -2211.19  349.11  2560.299 -17.381  79.653
     Variable  Count        Sum       Min      Max    Range   Mean  StdDev
0  streamflow   7976 -76435.303 -2238.621  239.318  2477.94 -9.583  73.688

lakeout

         Variable  Count        Sum       Min      Max     Range   Mean  StdDev
0  water_sfc_elev   5124   -554.709    -4.837    0.795     5.633 -0.108   0.267
1          inflow   5184 -33468.971 -2123.100  235.784  2358.884 -6.456  55.644
2         outflow   5118 -24772.443  -604.806   80.396   685.202 -4.840  25.740
         Variable  Count        Sum       Min      Max     Range   Mean  StdDev
0  water_sfc_elev   5121   -297.793    -5.922    0.869     6.792 -0.058   0.215
1          inflow   5184 -13091.676 -2484.207  202.132  2686.339 -2.525  51.031
2         outflow   5115 -15499.445 -1106.538   42.454  1148.991 -3.030  24.307

gwout

  Variable    Count          Sum     Min     Max   Range   Mean  StdDev
0  outflow  2724837   158617.749 -52.146   4.825  56.971  0.058   0.147
1    depth  2724837  2518710.806  -4.354  43.796  48.150  0.924   2.015
  Variable    Count          Sum     Min     Max   Range   Mean  StdDev
0  outflow  2724832    65530.238 -34.304   3.244  37.548  0.024   0.087
1    depth  2724837  1242587.835  -2.944  43.787  46.730  0.456   1.395

restart_hydro

None
     Variable    Count          Sum       Min      Max     Range   Mean  StdDev
0       hlink  2745286   120932.399   -44.844    9.954    54.798  0.044   0.606
1      qlink1  2685438 -6895576.734 -2436.044  428.897  2864.941 -2.568  36.328
2      qlink2  2685438 -6895576.734 -2436.044  428.897  2864.941 -2.568  36.328
3       resht     5124     -554.709    -4.837    0.795     5.633 -0.108   0.267
4      qlakeo     5118   -24772.443  -604.806   80.396   685.202 -4.840  25.740
5      qlakei     5184   -33468.971 -2123.100  235.784  2358.884 -6.456  55.644
6  z_gwsubbas  2724837     2518.711    -0.004    0.044     0.048  0.001   0.002
     Variable    Count          Sum       Min      Max     Range   Mean  StdDev
0       hlink  2739774   175008.271   -38.326    6.697    45.023  0.064   0.444
1      qlink1  2685413 -4373101.503 -2368.893  268.248  2637.141 -1.628  33.486
2      qlink2  2685413 -4373101.503 -2368.893  268.248  2637.141 -1.628  33.486
3       resht     5121     -297.793    -5.922    0.869     6.792 -0.058   0.215
4      qlakeo     5115   -15499.445 -1106.538   42.454  1148.991 -3.030  24.307
5      qlakei     5184   -13091.676 -2484.207  202.132  2686.339 -2.525  51.031
6  z_gwsubbas  2724837     1242.588    -0.003    0.044     0.047  0.000   0.001

restart_nudging

  Variable  Count  Sum  Min  Max  Range  Mean  StdDev
0    nudge     49  0.0  0.0  0.0    0.0   0.0     0.0
  Variable  Count  Sum  Min  Max  Range  Mean  StdDev
0    nudge     87  0.0  0.0  0.0    0.0   0.0     0.0
```

**Pull request merged**
