### PR TITLE
Updates to Reservoir Module Warnings and Errors 

### LINKED ISSUE #453: Updates to Reservoir Module Warnings and Errors
Updates needed for Reservoir Module Warnings and Errors

## Possible Solution
PR with updates to follow

### PR DESCRIPTION
**Pull request by jdmattern-noaa**
TYPE: choose one of [no impact, text only]

KEYWORDS: Reservoir Module, Warning/Error Handling

SOURCE: David Mattern - NOAA, @jdmattern-noaa 

DESCRIPTION OF CHANGES: Updates are added to how the reservoir module outputs warnings and handles errors

ISSUE: Fixes #453 

TESTS CONDUCTED: Reservoir unit tests conducted and passed.

NOTES: No changes to the functionality of the module other than passing more variables between functions.

### Checklist

 - [X] Closes issue #453  
 - [ ] Tests added (unit tests and/or regression/integration tests)
 - [ ] Backwards compatible
 - [ ] Requires new files? If so, how to generate them.
 - [ ] Fully documented
 - [ ] Short description in the Development section of `NEWS.md`

### CODE REVIEW

**Comment by jdmattern-noaa** [comment]
> Ryan and/or others probably have more context re: code changes here and how the logging was done (I'm guessing this was driven by some constraints / design ideas I'm not aware of) so I'll let them comment on that if needed.
> 
> I did note a number of really long lines of code though while skimming through this. It'd be nice if we could keep things under the 132 character Fortran standard at least. I know this (or the 100 character limit in the style guide) hasn't been enforced, but the very long lines do make the code harder to read. Some of these are starting to get close to or over 200 characters.

Thanks Katelyn. I can break those lines up if you and/or Ryan would like.

**Comment by rcabell** [comment]
Agree, these should be broken up. http://fortranwiki.org/fortran/show/Continuation+lines may be of use here.

**Comment by jdmattern-noaa** [comment]
> Agree, these should be broken up. http://fortranwiki.org/fortran/show/Continuation+lines may be of use here.

Ok will do.

**Comment by jdmattern-noaa** [comment]
I broke up those lines and pushed the changes.

**Pull request merged**
