### PR TITLE
Some testing improvements

### PR DESCRIPTION
**Pull request by jmccreight**

### CODE REVIEW

**Comment by jmccreight** [comment]
This PR passes locally. But we should scrutinize the failures here a bit before merging.

**Comment by jmills-ncar** [comment]
maybe I am missing it but it appears that th output frequency is 1 hour everywhere?

**Comment by jmccreight** [comment]
Yes, I set it to that since I don think that's the killer in time. That's just a change in the namelists.

**Comment by jmills-ncar** [comment]
Reopening from my fork to address comments

**Pull request closed without merging**
