### PR TITLE
add Analysis and Long namelist files reforecast v2.0

### PR DESCRIPTION
**Pull request by champham**

### CODE REVIEW

**Comment by jmccreight** [comment]
@champham 
I see the AnA_extended restart frequency is 4 hours and the total time is 28 hours. Which restart is used for the next AnA cycle? is it at 24 hours?

**Comment by champham** [comment]
James,

The extended AnA model uses the previous day 12Z restart file.

For example, the 16Z 9/25 extended AnA cycle runs from 12Z 9/24 to 16Z
9/25.  It starts by reading in the 12Z 9/24 restart file produced by the
previous day's extended AnA model run.  As it runs it produces a 12Z 9/25
restart file for use by tomorrow's (16Z 9/26) extended AnA cycle, and a 16Z
9/25 restart file that will be used by the 19Z 9/25 normal AnA.

Cham

**Comment by jmccreight** [comment]
screen shot 2018-09-26 at 10 00 33 am
I just wanted to document how the extended analysis works

**Comment by champham** [comment]
16Z extended analysis cycle runs that will produce 12Z and 16Z output restart files.

**Pull request merged**
