### PR TITLE
Introducing openmp

### PR DESCRIPTION
**Pull request by afanfa**
This PR introduces some OpenMP in the initialization phase.
This optimization makes a difference when a small number of processes (<= 64) are used.

On Cheyenne, the optimized version completes a eight hours CONUS simulation in 33 minutes and 51 seconds using 64 processes. The version currently on master completes the same simulation in 36 minutes and 28 seconds.
The results produced by the optimized version are identical to the ones produced by the version on master"

```
elfanfa@cheyenne3 /glade/flash/elfanfa/tmp_conus_performance_omp/run $ diff RESTART.2018060106_DOMAIN1 ../../tmp_conus_performance/run/RESTART.2018060106_DOMAIN1 
elfanfa@cheyenne3 /glade/flash/elfanfa/tmp_conus_performance_omp/run $ diff HYDRO_RST.2018-06-01_06\:00_DOMAIN1 ../../tmp_conus_performance/run/HYDRO_RST.2018-06-01_06\:00_DOMAIN1
```

### CODE REVIEW

**Comment by rcabell** [comment]
I resolved the merge conflicts to the best my of  understanding of what the existing code was doing. @jmccreight, you might want to verify that the Bash-related resolve is ok.

**Comment by jmccreight** [comment]
Hmm. The merge conflicts are vague to me now, hard to tell. I didnt notice there were merge conficts, they must have resulted from subsequent PRs on master.

**Comment by kafitzgerald** [comment]
Sorry, must've missed this notification, but just took a look.  I'm a bit confused about what the intent is here with respect to compiler options (particularly option 5).  It looks like @afanfa took out the 5/"intel.cray_xc" option (I'm new enough that I'm not aware of the machine / use case for this) and replaced it with a "hidden" option for Intel w/ OpenMP but then @rcabell tried to add it back in to resolve the merge conflict.  If someone (@afanfa or @jmccreight) can clarify what the intent is re: option 5, it should be easy to clean up.

**Comment by afanfa** [comment]
TheArgument for Cray should be 6, not 5. That is not part of my PR.

**Comment by rcabell** [comment]
@kafitzgerald, @afanfa  : Would changing line 126 in `configure` to:

```
fi

if [[ "$theArgument" == "6" ]] || [[ "$theArgument" == "intel.cray_xc" ]]; then
```

fix it?

**Comment by afanfa** [comment]
@rcabell I believe so.

**Comment by rcabell** [comment]
Should this have been closed without being merged?

**Comment by afanfa** [comment]
Sorry, I had deleted my branch by mistake. Not it's restored. The PR is still good on my side.

**Comment by rcabell** [comment]
@afanfa, @kafitzgerald : the Travis build is now failing. I may have a chance to look into it more this afternoon but if one of you can take a look sooner, please do.

**Pull request merged**
